[package]
name = "hydro"
version = "0.1.0"
authors = ["doamatto (Ronchetto, Matthew) <hello@doamatto.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
